"""alterar_quantidade_e_porcoes_para_decimal

Revision ID: 1fe1d1547c32
Revises: bf1e4ca961b0
Create Date: 2025-10-03 15:54:29.218475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe1d1547c32'
down_revision: Union[str, Sequence[str], None] = 'bf1e4ca961b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxonomia_aliases_id'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_alternativo'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_normalizado'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_taxonomia_id'), table_name='taxonomia_aliases')
    op.drop_table('taxonomia_aliases')
    op.alter_column('fornecedor_insumos', 'quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               comment='Quantidade de unidades vendidas pelo fornecedor (até 3 casas decimais)',
               existing_comment='Quantidade de unidades vendidas pelo fornecedor',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('receita_insumos', 'quantidade_necessaria',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_comment='Quantidade necessária do insumo (aceita decimais)',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'custo_calculado',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_comment='Custo deste insumo na receita em reais',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('receitas', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único da receita',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('receitas_id_seq'::regclass)"))
    op.alter_column('receitas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de criação automática',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('receitas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data da última atualização automática',
               existing_nullable=True)
    op.alter_column('receitas', 'grupo',
               existing_type=sa.VARCHAR(length=100),
               comment='Grupo/categoria da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'subgrupo',
               existing_type=sa.VARCHAR(length=100),
               comment='Subcategoria da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'sugestao_valor',
               existing_type=sa.INTEGER(),
               comment='Sugestão manual de preço pelo restaurante em centavos',
               existing_nullable=True)
    op.alter_column('receitas', 'rendimento_porcoes',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               comment='Rendimento em porções (até 3 casas decimais)',
               existing_comment='Rendimento em porções',
               existing_nullable=True)
    op.drop_index(op.f('idx_receitas_processada'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_codigo'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_grupo'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_subgrupo'), table_name='receitas')
    op.create_unique_constraint(None, 'receitas', ['codigo'])
    op.drop_column('receitas', 'unidade')
    op.drop_column('receitas', 'preco_compra')
    op.drop_column('receitas', 'quantidade')
    op.drop_column('receitas', 'fator')
    op.alter_column('restaurantes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do restaurante/rede',
               existing_comment='Nome do restaurante',
               existing_nullable=False)
    op.alter_column('restaurantes', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Tipo: restaurante, bar, quiosque, lanchonete, etc.',
               existing_server_default=sa.text("'restaurante'::character varying"))
    op.alter_column('restaurantes', 'endereco',
               existing_type=sa.TEXT(),
               comment='Endereço (rua, número)',
               existing_comment='Endereço completo do restaurante',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurantes', 'endereco',
               existing_type=sa.TEXT(),
               comment='Endereço completo do restaurante',
               existing_comment='Endereço (rua, número)',
               existing_nullable=True)
    op.alter_column('restaurantes', 'tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='Tipo: restaurante, bar, quiosque, lanchonete, etc.',
               existing_server_default=sa.text("'restaurante'::character varying"))
    op.alter_column('restaurantes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do restaurante',
               existing_comment='Nome do restaurante/rede',
               existing_nullable=False)
    op.add_column('receitas', sa.Column('fator', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receitas', sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('receitas', sa.Column('preco_compra', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('receitas', sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receitas', type_='unique')
    op.create_index(op.f('ix_receitas_subgrupo'), 'receitas', ['subgrupo'], unique=False)
    op.create_index(op.f('ix_receitas_grupo'), 'receitas', ['grupo'], unique=False)
    op.create_index(op.f('ix_receitas_codigo'), 'receitas', ['codigo'], unique=True)
    op.create_index(op.f('idx_receitas_processada'), 'receitas', ['processada'], unique=False)
    op.alter_column('receitas', 'rendimento_porcoes',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               comment='Rendimento em porções',
               existing_comment='Rendimento em porções (até 3 casas decimais)',
               existing_nullable=True)
    op.alter_column('receitas', 'sugestao_valor',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sugestão manual de preço pelo restaurante em centavos',
               existing_nullable=True)
    op.alter_column('receitas', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nome da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código único da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'subgrupo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Subcategoria da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'grupo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Grupo/categoria da receita',
               existing_nullable=False)
    op.alter_column('receitas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data da última atualização automática',
               existing_nullable=True)
    op.alter_column('receitas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de criação automática',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('receitas', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único da receita',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('receitas_id_seq'::regclass)"))
    op.alter_column('receita_insumos', 'custo_calculado',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='Custo deste insumo na receita em reais',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('receita_insumos', 'quantidade_necessaria',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_comment='Quantidade necessária do insumo (aceita decimais)',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'quantidade',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               comment='Quantidade de unidades vendidas pelo fornecedor',
               existing_comment='Quantidade de unidades vendidas pelo fornecedor (até 3 casas decimais)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_table('taxonomia_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('taxonomia_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID da taxonomia de destino'),
    sa.Column('nome_alternativo', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome alternativo que mapeia para a taxonomia'),
    sa.Column('nome_normalizado', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Versão normalizada do nome (minúsculo, sem acentos)'),
    sa.Column('tipo_alias', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Tipo: manual, automatico, importacao, ia'),
    sa.Column('confianca', sa.INTEGER(), autoincrement=False, nullable=False, comment='Nível de confiança do mapeamento (0-100)'),
    sa.Column('origem', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Origem do alias (fornecedor, sistema, usuário, etc.)'),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True, comment='Observações sobre o mapeamento'),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Se o alias está ativo para uso'),
    sa.ForeignKeyConstraint(['taxonomia_id'], ['taxonomias.id'], name=op.f('taxonomia_aliases_taxonomia_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('taxonomia_aliases_pkey')),
    sa.UniqueConstraint('nome_alternativo', name=op.f('uq_taxonomia_alias_nome_alternativo'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome_normalizado', name=op.f('uq_taxonomia_alias_nome_normalizado'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_taxonomia_aliases_taxonomia_id'), 'taxonomia_aliases', ['taxonomia_id'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_normalizado'), 'taxonomia_aliases', ['nome_normalizado'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_alternativo'), 'taxonomia_aliases', ['nome_alternativo'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_id'), 'taxonomia_aliases', ['id'], unique=False)
    # ### end Alembic commands ###
