"""Criar tabela users completa com roles

Revision ID: 52fb5e3cc39b
Revises: abd442e8b201
Create Date: 2025-10-20 13:15:05.870465

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52fb5e3cc39b'
down_revision: Union[str, Sequence[str], None] = 'abd442e8b201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Migration corrigida - verifica se tabelas já existem antes de criar.
    """
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Criar tabela taxonomia_aliases apenas se não existir
    if 'taxonomia_aliases' not in existing_tables:
        op.create_table('taxonomia_aliases',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
            sa.Column('taxonomia_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('nome_alternativo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
            sa.Column('nome_normalizado', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
            sa.Column('tipo_alias', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.Column('confianca', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('origem', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
            sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
            sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['taxonomia_id'], ['taxonomias.id'], name=op.f('taxonomia_aliases_taxonomia_id_fkey'), ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name=op.f('taxonomia_aliases_pkey')),
            sa.UniqueConstraint('nome_alternativo', name=op.f('uq_taxonomia_alias_nome_alternativo')),
            sa.UniqueConstraint('nome_normalizado', name=op.f('uq_taxonomia_alias_nome_normalizado'))
        )
        op.create_index(op.f('ix_taxonomia_aliases_id'), 'taxonomia_aliases', ['id'], unique=False)
        op.create_index(op.f('ix_taxonomia_aliases_nome_alternativo'), 'taxonomia_aliases', ['nome_alternativo'], unique=False)
        op.create_index(op.f('ix_taxonomia_aliases_nome_normalizado'), 'taxonomia_aliases', ['nome_normalizado'], unique=False)
        op.create_index(op.f('ix_taxonomia_aliases_taxonomia_id'), 'taxonomia_aliases', ['taxonomia_id'], unique=False)
        print("✅ Tabela taxonomia_aliases criada")
    else:
        print("⚠️  Tabela taxonomia_aliases já existe, pulando criação")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receitas', 'insumos_pendentes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de IDs dos insumos que estão sem preço',
               existing_comment='Lista de IDs dos insumos que estão sem preço (formato: [1, 5, 12])',
               existing_nullable=True)
    op.drop_column('receitas', 'fator')
    op.drop_column('receitas', 'quantidade')
    op.drop_column('receitas', 'unidade')
    op.drop_constraint(None, 'receita_insumos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receita_insumos_receita_processada'), 'receita_insumos', 'receitas', ['receita_processada_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_receita_insumos_receita_processada'), 'receita_insumos', ['receita_processada_id'], unique=False)
    op.alter_column('receita_insumos', 'receita_processada_id',
               existing_type=sa.INTEGER(),
               comment='ID da receita processada usada como insumo (quando aplicável)',
               existing_comment='ID da receita processada usada como insumo',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'insumo_id',
               existing_type=sa.INTEGER(),
               comment='ID do insumo',
               existing_comment='ID do insumo (NULL quando for receita processada)',
               existing_nullable=True)
    op.alter_column('insumos', 'preco_compra',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Preço de compra em centavos (NULL = sem preço definido)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomia_aliases_taxonomia_id'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_normalizado'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_alternativo'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_id'), table_name='taxonomia_aliases')
    op.drop_table('taxonomia_aliases')
    # ### end Alembic commands ###
