"""Criar tabela users completa com roles

Revision ID: 52fb5e3cc39b
Revises: abd442e8b201
Create Date: 2025-10-20 13:15:05.870465

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52fb5e3cc39b'
down_revision: Union[str, Sequence[str], None] = 'abd442e8b201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Verificar se o ENUM já existe antes de criar
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Criar ENUM apenas se não existir
    if 'userrole' not in [e['name'] for e in inspector.get_enums()]:
        sa.Enum('ADMIN', 'CONSULTANT', 'STORE', name='userrole').create(bind)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomia_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taxonomia_id', sa.Integer(), nullable=False, comment='ID da taxonomia de destino'),
    sa.Column('nome_alternativo', sa.String(length=255), nullable=False, comment='Nome alternativo que mapeia para a taxonomia'),
    sa.Column('nome_normalizado', sa.String(length=255), nullable=False, comment='Versão normalizada do nome (minúsculo, sem acentos)'),
    sa.Column('tipo_alias', sa.String(length=50), nullable=False, comment='Tipo: manual, automatico, importacao, ia'),
    sa.Column('confianca', sa.Integer(), nullable=False, comment='Nível de confiança do mapeamento (0-100)'),
    sa.Column('origem', sa.String(length=100), nullable=True, comment='Origem do alias (fornecedor, sistema, usuário, etc.)'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações sobre o mapeamento'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Se o alias está ativo para uso'),
    sa.ForeignKeyConstraint(['taxonomia_id'], ['taxonomias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_alternativo', name='uq_taxonomia_alias_nome_alternativo'),
    sa.UniqueConstraint('nome_normalizado', name='uq_taxonomia_alias_nome_normalizado')
    )
    op.create_index(op.f('ix_taxonomia_aliases_id'), 'taxonomia_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_alternativo'), 'taxonomia_aliases', ['nome_alternativo'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_normalizado'), 'taxonomia_aliases', ['nome_normalizado'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_taxonomia_id'), 'taxonomia_aliases', ['taxonomia_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nome de usuário único para login'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Senha criptografada com bcrypt'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email do usuário (opcional, para recuperação de senha futura)'),
    sa.Column('role', postgresql.ENUM('ADMIN', 'CONSULTANT', 'STORE', name='userrole', create_type=False), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=True, comment='Restaurante vinculado (obrigatório para STORE, opcional para outros)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Status do usuário: True = ativo, False = inativo'),
    sa.Column('primeiro_acesso', sa.Boolean(), nullable=False, comment='Flag para forçar troca de senha no primeiro acesso'),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True, comment='Data e hora do último login'),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('insumos', 'preco_compra',
               existing_type=sa.INTEGER(),
               comment='Preço de compra em centavos (NULL = sem preço definido)',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'insumo_id',
               existing_type=sa.INTEGER(),
               comment='ID do insumo (NULL quando for receita processada)',
               existing_comment='ID do insumo',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'receita_processada_id',
               existing_type=sa.INTEGER(),
               comment='ID da receita processada usada como insumo',
               existing_comment='ID da receita processada usada como insumo (quando aplicável)',
               existing_nullable=True)
    op.drop_index(op.f('idx_receita_insumos_receita_processada'), table_name='receita_insumos')
    op.drop_constraint(op.f('fk_receita_insumos_receita_processada'), 'receita_insumos', type_='foreignkey')
    op.create_foreign_key(None, 'receita_insumos', 'receitas', ['receita_processada_id'], ['id'])
    op.add_column('receitas', sa.Column('unidade', sa.String(length=20), nullable=True, comment='Unidade de medida da receita (kg, L, un, etc)'))
    op.add_column('receitas', sa.Column('quantidade', sa.Integer(), nullable=True, comment='Quantidade base que a receita produz'))
    op.add_column('receitas', sa.Column('fator', sa.Float(), nullable=True, comment='Fator de conversão para cálculos'))
    op.alter_column('receitas', 'insumos_pendentes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de IDs dos insumos que estão sem preço (formato: [1, 5, 12])',
               existing_comment='Lista de IDs dos insumos que estão sem preço',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receitas', 'insumos_pendentes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Lista de IDs dos insumos que estão sem preço',
               existing_comment='Lista de IDs dos insumos que estão sem preço (formato: [1, 5, 12])',
               existing_nullable=True)
    op.drop_column('receitas', 'fator')
    op.drop_column('receitas', 'quantidade')
    op.drop_column('receitas', 'unidade')
    op.drop_constraint(None, 'receita_insumos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receita_insumos_receita_processada'), 'receita_insumos', 'receitas', ['receita_processada_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_receita_insumos_receita_processada'), 'receita_insumos', ['receita_processada_id'], unique=False)
    op.alter_column('receita_insumos', 'receita_processada_id',
               existing_type=sa.INTEGER(),
               comment='ID da receita processada usada como insumo (quando aplicável)',
               existing_comment='ID da receita processada usada como insumo',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'insumo_id',
               existing_type=sa.INTEGER(),
               comment='ID do insumo',
               existing_comment='ID do insumo (NULL quando for receita processada)',
               existing_nullable=True)
    op.alter_column('insumos', 'preco_compra',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Preço de compra em centavos (NULL = sem preço definido)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomia_aliases_taxonomia_id'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_normalizado'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_nome_alternativo'), table_name='taxonomia_aliases')
    op.drop_index(op.f('ix_taxonomia_aliases_id'), table_name='taxonomia_aliases')
    op.drop_table('taxonomia_aliases')
    # ### end Alembic commands ###
