"""Adicionar campo aguardando_classificacao ao modelo Insumo

Revision ID: 6e084e709b5e
Revises: 
Create Date: 2025-09-11 15:00:51.138497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e084e709b5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drops resilientes com IF EXISTS para compatibilidade com produção
    op.execute("DROP TABLE IF EXISTS fornecedor_insumos_backup")
    op.execute("DROP TABLE IF EXISTS taxonomia_aliases CASCADE")
    op.execute("DROP TABLE IF EXISTS log_mudancas_preco CASCADE")
    op.execute("DROP TABLE IF EXISTS insumos_backup")
    
    # Drop de índices de forma resiliente
    op.execute("DROP INDEX IF EXISTS idx_fornecedor_insumos_codigo")
    op.execute("DROP INDEX IF EXISTS idx_fornecedor_insumos_fornecedor")
    op.execute("DROP INDEX IF EXISTS idx_fornecedor_insumos_nome")
    op.execute("DROP INDEX IF EXISTS idx_fornecedores_cpf_cnpj")
    op.execute("DROP INDEX IF EXISTS idx_fornecedores_estado")
    op.execute("DROP INDEX IF EXISTS idx_fornecedores_nome")
    op.execute("DROP INDEX IF EXISTS idx_insumos_anonimo")
    op.execute("DROP INDEX IF EXISTS idx_insumos_fornecedor_id")
    op.execute("DROP INDEX IF EXISTS idx_insumos_fornecedor_insumo")
    op.execute("DROP INDEX IF EXISTS idx_insumos_subgrupo")
    op.execute("DROP INDEX IF EXISTS idx_insumos_taxonomia_id")
    
    # Alter columns - fornecedor_insumos
    op.alter_column('fornecedor_insumos', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               comment='ID do fornecedor que oferece este insumo',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='Código do insumo no catálogo do fornecedor',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do insumo oferecido pelo fornecedor',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'unidade',
               existing_type=sa.VARCHAR(length=20),
               comment='Unidade de medida (kg, g, L, ml, unidade, etc.)',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'preco_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Preço por unidade oferecido pelo fornecedor (em reais)',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'descricao',
               existing_type=sa.TEXT(),
               comment='Descrição detalhada do insumo (opcional)',
               existing_nullable=True)
    op.alter_column('fornecedor_insumos', 'quantidade',
               existing_type=sa.INTEGER(),
               comment='Quantidade de unidades vendidas pelo fornecedor',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('fornecedor_insumos', 'fator',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Fator para conversão (ex: 0.75 para 750ml, 20.0 para caixa 20un)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    
    # Drop constraint resiliente
    op.execute("ALTER TABLE fornecedor_insumos DROP CONSTRAINT IF EXISTS uk_fornecedor_insumos_codigo")
    
    # Criar índices de forma resiliente
    op.execute("CREATE INDEX IF NOT EXISTS ix_fornecedor_insumos_id ON fornecedor_insumos (id)")
    
    # Alter columns - fornecedores
    op.alter_column('fornecedores', 'nome_razao_social',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome ou Razão Social do fornecedor',
               existing_nullable=False)
    op.alter_column('fornecedores', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato do fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'ramo',
               existing_type=sa.VARCHAR(length=100),
               comment='Ramo de atividade do fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade onde está localizado o fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'estado',
               existing_type=sa.VARCHAR(length=2),
               comment='Estado (UF) onde está localizado o fornecedor',
               existing_nullable=True)
    
    # Drop constraint resiliente
    op.execute("ALTER TABLE fornecedores DROP CONSTRAINT IF EXISTS uk_fornecedores_cpf_cnpj")
    
    # Criar índices de forma resiliente
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_fornecedores_cpf_cnpj ON fornecedores (cpf_cnpj)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_fornecedores_id ON fornecedores (id)")
    
    # Add column se não existir
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name='insumos' AND column_name='aguardando_classificacao') THEN
                ALTER TABLE insumos ADD COLUMN aguardando_classificacao BOOLEAN;
                COMMENT ON COLUMN insumos.aguardando_classificacao IS 'TRUE = aguardando classificação pela IA, FALSE = não precisa ou já classificado';
            END IF;
        END $$;
    """)
    
    op.alter_column('insumos', 'fornecedor_insumo_id',
               existing_type=sa.INTEGER(),
               comment='ID do insumo no catálogo do fornecedor (NULL = fornecedor anônimo)',
               existing_nullable=True)
    op.alter_column('insumos', 'eh_fornecedor_anonimo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='TRUE = sem fornecedor específico, FALSE = vinculado a fornecedor',
               existing_server_default=sa.text('true'))
    op.alter_column('insumos', 'taxonomia_id',
               existing_type=sa.INTEGER(),
               comment='ID da taxonomia hierárquica master (sistema de padronização)',
               existing_nullable=True)
    
    op.execute("CREATE INDEX IF NOT EXISTS ix_insumos_taxonomia_id ON insumos (taxonomia_id)")
    
    # Drop columns se existirem
    op.execute("ALTER TABLE insumos DROP COLUMN IF EXISTS fornecedor_id")
    op.execute("ALTER TABLE insumos DROP COLUMN IF EXISTS valor_compra_por_kg")
    op.execute("ALTER TABLE insumos DROP COLUMN IF EXISTS total_comprado")
    
    # Restante das alterações em receita_insumos, receitas, restaurantes e taxonomias
    op.alter_column('receita_insumos', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único do relacionamento',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('receita_insumos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de criação automática',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('receita_insumos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data da última atualização automática',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'receita_id',
               existing_type=sa.INTEGER(),
               comment='ID da receita',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'insumo_id',
               existing_type=sa.INTEGER(),
               comment='ID do insumo',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'quantidade_necessaria',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               comment='Quantidade necessária do insumo (aceita decimais)',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'unidade_medida',
               existing_type=sa.VARCHAR(length=20),
               comment='Unidade de medida (g, kg, ml, L, unidade)',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'custo_calculado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               comment='Custo deste insumo na receita em reais',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('receita_insumos', 'observacoes',
               existing_type=sa.TEXT(),
               comment='Observações sobre o uso deste insumo na receita',
               existing_nullable=True)
    
    op.execute("ALTER TABLE receita_insumos DROP COLUMN IF EXISTS ordem")
    
    op.alter_column('receitas', 'restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID do restaurante dono da receita')
    op.alter_column('receitas', 'cmv',
               existing_type=sa.INTEGER(),
               comment='Custo da mercadoria vendida em centavos',
               existing_nullable=True)
    op.alter_column('receitas', 'margem_percentual',
               existing_type=sa.INTEGER(),
               comment='Margem de lucro em porcentagem * 100',
               existing_nullable=True)
    op.alter_column('receitas', 'receita_pai_id',
               existing_type=sa.INTEGER(),
               comment='ID da receita pai para variações',
               existing_nullable=True)
    op.alter_column('receitas', 'variacao_nome',
               existing_type=sa.VARCHAR(length=100),
               comment="Nome da variação (ex: 'Sem Glúten', 'Extra Grande')",
               existing_nullable=True)
    op.alter_column('receitas', 'descricao',
               existing_type=sa.TEXT(),
               comment='Descrição detalhada da receita',
               existing_nullable=True)
    op.alter_column('receitas', 'modo_preparo',
               existing_type=sa.TEXT(),
               comment='Modo de preparo da receita',
               existing_nullable=True)
    op.alter_column('receitas', 'tempo_preparo_minutos',
               existing_type=sa.INTEGER(),
               comment='Tempo de preparo em minutos',
               existing_nullable=True)
    op.alter_column('receitas', 'rendimento_porcoes',
               existing_type=sa.INTEGER(),
               comment='Rendimento em porções',
               existing_nullable=True)
    op.alter_column('receitas', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='Se a receita está ativa no cardápio',
               existing_nullable=True)
    op.alter_column('receitas', 'fator',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    
    # Taxonomias
    op.alter_column('taxonomias', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               comment='Nível 1: Categoria principal (Carnes, Peixes, Verduras, etc.)',
               existing_nullable=False)
    op.alter_column('taxonomias', 'subcategoria',
               existing_type=sa.VARCHAR(length=100),
               comment='Nível 2: Subcategoria (Bovino, Salmão, Tomate, etc.)',
               existing_nullable=False)
    op.alter_column('taxonomias', 'especificacao',
               existing_type=sa.VARCHAR(length=100),
               comment='Nível 3: Especificação (Filé, Inteiro, Moído, Fresco, etc.)',
               existing_nullable=True)
    op.alter_column('taxonomias', 'variante',
               existing_type=sa.VARCHAR(length=100),
               comment='Nível 4: Variante (Premium, Orgânico, Marca específica, etc.)',
               existing_nullable=True)
    op.alter_column('taxonomias', 'nome_completo',
               existing_type=sa.VARCHAR(length=500),
               comment="Path completo: 'Categoria > Subcategoria > Especificação > Variante'",
               existing_nullable=False)
    op.alter_column('taxonomias', 'codigo_taxonomia',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único gerado: CAR-BOV-FIL-PREM',
               existing_nullable=False)
    op.alter_column('taxonomias', 'descricao',
               existing_type=sa.TEXT(),
               comment='Descrição detalhada da taxonomia',
               existing_nullable=True)
    op.alter_column('taxonomias', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='Se a taxonomia está ativa para uso',
               existing_nullable=False)
    
    # Constraint resiliente
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_taxonomia_completa') THEN
                ALTER TABLE taxonomias ADD CONSTRAINT uq_taxonomia_completa 
                UNIQUE (categoria, subcategoria, especificacao, variante);
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_taxonomia_completa', 'taxonomias', type_='unique')
    op.alter_column('taxonomias', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se a taxonomia está ativa para uso',
               existing_nullable=False)
    op.alter_column('taxonomias', 'descricao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada da taxonomia',
               existing_nullable=True)
    op.alter_column('taxonomias', 'codigo_taxonomia',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código único gerado: CAR-BOV-FIL-PREM',
               existing_nullable=False)
    op.alter_column('taxonomias', 'nome_completo',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="Path completo: 'Categoria > Subcategoria > Especificação > Variante'",
               existing_nullable=False)
    op.alter_column('taxonomias', 'variante',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nível 4: Variante (Premium, Orgânico, Marca específica, etc.)',
               existing_nullable=True)
    op.alter_column('taxonomias', 'especificacao',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nível 3: Especificação (Filé, Inteiro, Moído, Fresco, etc.)',
               existing_nullable=True)
    op.alter_column('taxonomias', 'subcategoria',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nível 2: Subcategoria (Bovino, Salmão, Tomate, etc.)',
               existing_nullable=False)
    op.alter_column('taxonomias', 'categoria',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nível 1: Categoria principal (Carnes, Peixes, Verduras, etc.)',
               existing_nullable=False)
    op.alter_column('restaurantes', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se o restaurante está ativo',
               existing_nullable=True)
    op.alter_column('restaurantes', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('restaurantes', 'endereco',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Endereço completo do restaurante',
               existing_nullable=True)
    op.alter_column('restaurantes', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment=None,
               existing_comment='CNPJ do restaurante',
               existing_nullable=True)
    op.alter_column('restaurantes', 'nome',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Nome do restaurante',
               existing_nullable=False)
    op.alter_column('restaurantes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data da última atualização automática',
               existing_nullable=True)
    op.alter_column('restaurantes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de criação automática',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurantes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único do restaurante',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'receitas', type_='foreignkey')
    op.alter_column('receitas', 'fator',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('receitas', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Se a receita está ativa no cardápio',
               existing_nullable=True)
    op.alter_column('receitas', 'rendimento_porcoes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Rendimento em porções',
               existing_nullable=True)
    op.alter_column('receitas', 'tempo_preparo_minutos',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tempo de preparo em minutos',
               existing_nullable=True)
    op.alter_column('receitas', 'modo_preparo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Modo de preparo da receita',
               existing_nullable=True)
    op.alter_column('receitas', 'descricao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada da receita',
               existing_nullable=True)
    op.alter_column('receitas', 'variacao_nome',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Nome da variação (ex: 'Sem Glúten', 'Extra Grande')",
               existing_nullable=True)
    op.alter_column('receitas', 'receita_pai_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID da receita pai para variações',
               existing_nullable=True)
    op.alter_column('receitas', 'margem_percentual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Margem de lucro em porcentagem * 100',
               existing_nullable=True)
    op.alter_column('receitas', 'cmv',
               existing_type=sa.INTEGER(),
               comment='Custo da Mercadoria Vendida em centavos',
               existing_comment='Custo da mercadoria vendida em centavos',
               existing_nullable=True)
    # Primeiro, corrigir receitas sem restaurante_id
    op.execute("UPDATE receitas SET restaurante_id = 1 WHERE restaurante_id IS NULL")

    op.alter_column('receitas', 'restaurante_id',
                existing_type=sa.INTEGER(),
                nullable=True,
                comment=None,
                existing_comment='ID do restaurante dono da receita')
    op.add_column('receita_insumos', sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('receita_insumos', 'observacoes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Observações sobre o uso deste insumo na receita',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'custo_calculado',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Custo deste insumo na receita em reais',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('receita_insumos', 'unidade_medida',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unidade de medida (g, kg, ml, L, unidade)',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'quantidade_necessaria',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade necessária do insumo (aceita decimais)',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'insumo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do insumo',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'receita_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID da receita',
               existing_nullable=False)
    op.alter_column('receita_insumos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data da última atualização automática',
               existing_nullable=True)
    op.alter_column('receita_insumos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de criação automática',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('receita_insumos', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único do relacionamento',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('insumos', sa.Column('total_comprado', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True, comment='Total comprado (quantidade * valor_compra_por_kg)'))
    op.add_column('insumos', sa.Column('valor_compra_por_kg', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True, comment='Valor de compra por Kg em reais'))
    op.add_column('insumos', sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_insumos_taxonomia_id'), table_name='insumos')
    op.create_index(op.f('idx_insumos_taxonomia_id'), 'insumos', ['taxonomia_id'], unique=False)
    op.create_index(op.f('idx_insumos_subgrupo'), 'insumos', ['subgrupo'], unique=False)
    op.create_index(op.f('idx_insumos_fornecedor_insumo'), 'insumos', ['fornecedor_insumo_id'], unique=False)
    op.create_index(op.f('idx_insumos_fornecedor_id'), 'insumos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('idx_insumos_anonimo'), 'insumos', ['eh_fornecedor_anonimo'], unique=False)
    op.alter_column('insumos', 'taxonomia_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID da taxonomia hierárquica master (sistema de padronização)',
               existing_nullable=True)
    op.alter_column('insumos', 'eh_fornecedor_anonimo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='TRUE = sem fornecedor específico, FALSE = vinculado a fornecedor',
               existing_server_default=sa.text('true'))
    op.alter_column('insumos', 'fornecedor_insumo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do insumo no catálogo do fornecedor (NULL = fornecedor anônimo)',
               existing_nullable=True)
    op.drop_column('insumos', 'aguardando_classificacao')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cpf_cnpj'), table_name='fornecedores')
    op.create_unique_constraint(op.f('uk_fornecedores_cpf_cnpj'), 'fornecedores', ['cpf_cnpj'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_fornecedores_nome'), 'fornecedores', ['nome_razao_social'], unique=False)
    op.create_index(op.f('idx_fornecedores_estado'), 'fornecedores', ['estado'], unique=False)
    op.create_index(op.f('idx_fornecedores_cpf_cnpj'), 'fornecedores', ['cpf_cnpj'], unique=False)
    op.alter_column('fornecedores', 'estado',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='Estado (UF) onde está localizado o fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'cidade',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Cidade onde está localizado o fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'ramo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Ramo de atividade do fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Telefone de contato do fornecedor',
               existing_nullable=True)
    op.alter_column('fornecedores', 'nome_razao_social',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nome ou Razão Social do fornecedor',
               existing_nullable=False)
    op.create_table_comment(
        'fornecedor_insumos',
        'Catálogo de insumos oferecidos por cada fornecedor',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_fornecedor_insumos_id'), table_name='fornecedor_insumos')
    op.create_unique_constraint(op.f('uk_fornecedor_insumos_codigo'), 'fornecedor_insumos', ['fornecedor_id', 'codigo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_fornecedor_insumos_nome'), 'fornecedor_insumos', ['nome'], unique=False)
    op.create_index(op.f('idx_fornecedor_insumos_fornecedor'), 'fornecedor_insumos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('idx_fornecedor_insumos_codigo'), 'fornecedor_insumos', ['codigo'], unique=False)
    op.alter_column('fornecedor_insumos', 'fator',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment=None,
               existing_comment='Fator para conversão (ex: 0.75 para 750ml, 20.0 para caixa 20un)',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('fornecedor_insumos', 'quantidade',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade de unidades vendidas pelo fornecedor',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('fornecedor_insumos', 'descricao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada do insumo (opcional)',
               existing_nullable=True)
    op.alter_column('fornecedor_insumos', 'preco_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Preço por unidade oferecido pelo fornecedor (em reais)',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'unidade',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unidade de medida (kg, g, L, ml, unidade, etc.)',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Nome do insumo oferecido pelo fornecedor',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código do insumo no catálogo do fornecedor',
               existing_nullable=False)
    op.alter_column('fornecedor_insumos', 'fornecedor_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID do fornecedor que oferece este insumo',
               existing_nullable=False)
    op.create_table('insumos_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subgrupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fator', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('preco_compra', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_compra_por_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_comprado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fornecedor_insumo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eh_fornecedor_anonimo', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('log_mudancas_preco',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('insumo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_anterior', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('preco_novo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentual_mudanca', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('fornecedor_preco_referencia', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_mudanca', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], name=op.f('fk_log_preco_insumo'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('log_mudancas_preco_pkey')),
    comment='Log de mudanças de preços de insumos para auditoria'
    )
    op.create_index(op.f('idx_log_preco_insumo'), 'log_mudancas_preco', ['insumo_id'], unique=False)
    op.create_index(op.f('idx_log_preco_data'), 'log_mudancas_preco', ['data_mudanca'], unique=False)
    op.create_table('taxonomia_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('taxonomia_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID da taxonomia de destino'),
    sa.Column('nome_alternativo', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nome alternativo que mapeia para a taxonomia'),
    sa.Column('nome_normalizado', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Versão normalizada do nome (minúsculo, sem acentos)'),
    sa.Column('tipo_alias', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Tipo: manual, automatico, importacao, ia'),
    sa.Column('confianca', sa.INTEGER(), autoincrement=False, nullable=False, comment='Nível de confiança do mapeamento (0-100)'),
    sa.Column('origem', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Origem do alias (fornecedor, sistema, usuário, etc.)'),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True, comment='Observações sobre o mapeamento'),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Se o alias está ativo para uso'),
    sa.ForeignKeyConstraint(['taxonomia_id'], ['taxonomias.id'], name=op.f('taxonomia_aliases_taxonomia_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('taxonomia_aliases_pkey')),
    sa.UniqueConstraint('nome_alternativo', name=op.f('uq_taxonomia_alias_nome_alternativo'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('nome_normalizado', name=op.f('uq_taxonomia_alias_nome_normalizado'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_taxonomia_aliases_taxonomia_id'), 'taxonomia_aliases', ['taxonomia_id'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_normalizado'), 'taxonomia_aliases', ['nome_normalizado'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_nome_alternativo'), 'taxonomia_aliases', ['nome_alternativo'], unique=False)
    op.create_index(op.f('ix_taxonomia_aliases_id'), 'taxonomia_aliases', ['id'], unique=False)
    op.create_table('fornecedor_insumos_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fator', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
