"""permite restaurante_id null para insumos globais

Revision ID: 918a2fc23a38
Revises: b07e1b96757e
Create Date: 2025-10-27 12:08:30.000052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918a2fc23a38'
down_revision: Union[str, Sequence[str], None] = 'b07e1b96757e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insumos', 'restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID do restaurante proprietário do insumo (NULL = insumo global)',
               existing_comment='ID do restaurante proprietário do insumo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insumos', 'restaurante_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID do restaurante proprietário do insumo',
               existing_comment='ID do restaurante proprietário do insumo (NULL = insumo global)')
    # ### end Alembic commands ###
