"""remove campo fator de insumos

Revision ID: b07e1b96757e
Revises: 99c4d630b473
Create Date: 2025-10-24 17:50:59.149809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b07e1b96757e'
down_revision: Union[str, Sequence[str], None] = '99c4d630b473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumos', 'fator')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'CONSULTANT', 'STORE', 'OWNER', 'MANAGER', 'OPERATOR', name='userrole'),
               comment='Perfil do usuário: ADMIN, CONSULTANT, OWNER, MANAGER, OPERATOR',
               existing_nullable=False)
    op.alter_column('users', 'restaurante_id',
               existing_type=sa.INTEGER(),
               comment='Restaurante vinculado (obrigatório para PROPRIETÁRIO, GERENTE E OPERADOR, opcional para outros)',
               existing_comment='Restaurante vinculado (obrigatório para STORE, opcional para outros)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'restaurante_id',
               existing_type=sa.INTEGER(),
               comment='Restaurante vinculado (obrigatório para STORE, opcional para outros)',
               existing_comment='Restaurante vinculado (obrigatório para PROPRIETÁRIO, GERENTE E OPERADOR, opcional para outros)',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'CONSULTANT', 'STORE', 'OWNER', 'MANAGER', 'OPERATOR', name='userrole'),
               comment=None,
               existing_comment='Perfil do usuário: ADMIN, CONSULTANT, OWNER, MANAGER, OPERATOR',
               existing_nullable=False)
    op.add_column('insumos', sa.Column('fator', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
